### ISSUE TITLE
the game froze twice right after level 10

### ISSUE THREAD

**Issue by devoncarew** [flutter/game#38]
Music kept playing, but the animation stopped and the app was non-responsive.

**Comment by jwren** [comment]
Same happened to me- nexus 6p

**Comment by devoncarew** [comment]
Don't know if this is the problem, but I do see this issue when I run `flutter logs`:

```
android: I/flutter : -- EXCEPTION CAUGHT BY SCHEDULER LIBRARY -------------------------------
android: I/flutter : An exception was raised during a scheduler callback:
android: I/flutter : The null object does not have a method '[]'.
android: I/flutter : NoSuchMethodError: method not found: '[]'
android: I/flutter : Receiver: null
android: I/flutter : Arguments: [0]
android: I/flutter : Stack trace:
android: I/flutter : #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
android: I/flutter : #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
android: I/flutter : #2      GameObjectFactory.addEnemyScoutSwarm (/Volumes/Dev/game/lib/game_object_factory.dart:44)
android: I/flutter : #3      GameDemoNode.addLevelChunk (/Volumes/Dev/game/lib/game_demo_node.dart:208)
android: I/flutter : #4      GameDemoNode.addObjects (/Volumes/Dev/game/lib/game_demo_node.dart:187)
android: I/flutter : #5      GameDemoNode.update (/Volumes/Dev/game/lib/game_demo_node.dart:107)
android: I/flutter : #6      SpriteBox._callUpdate (packages/flutter_sprites/src/sprite_box.dart:419)
android: I/flutter : #7      SpriteBox._tick (packages/flutter_sprites/src/sprite_box.dart:381)
android: I/flutter : #8      BindingBase&Scheduler.invokeFrameCallback (packages/flutter/src/scheduler/scheduler.dart:269)
android: I/flutter : #9      BindingBase&Scheduler._invokeTransientFrameCallbacks.<anonymous closure> (packages/flutter/src/scheduler/scheduler.dart:223)
android: I/flutter : #10     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:340)
android: I/flutter : #11     BindingBase&Scheduler._invokeTransientFrameCallbacks (packages/flutter/src/scheduler/scheduler.dart:221)
android: I/flutter : #12     BindingBase&Scheduler.handleBeginFrame (packages/flutter/src/scheduler/scheduler.dart:243)
android: I/flutter : #13     _beginFrame (file:///home/travis/build/flutter/buildbot/src/out/android_Release/gen/sky/bindings/hooks.dart:48)
android: I/flutter : ------------------------------------------------------------------------
```
