### ISSUE TITLE
Attempting flutter start on new nexus 9 causes stack trace

### ISSUE THREAD

**Issue by domesticmouse** [flutter/game#5]
Nexus 9 running Android 6.0 build MRA58K. All I can see is a blank red screen.

Reproduction steps:
```bash
$ dart --version
Dart VM version: 1.13.0 (Wed Nov 18 12:27:07 2015) on "linux_x64"
$ flutter --version
Flutter
Repository: https://github.com/flutter/flutter.git
Branch: alpha
Revision: 4472d06e022cd5fb604c83a850ff20d54073906b (30 hours ago)
$ git clone https://github.com/flutter/game.git
[...]
$ cd game
$ pub get
$ flutter start
$ flutter logs 
[lots of output skipped]
android: I/flutter : Exception caught while building TextureButton
android: I/flutter : No constructor 'CustomPaint' with matching arguments declared in class 'CustomPaint'.
android: I/flutter : NoSuchMethodError: incorrect number of arguments passed to method named 'CustomPaint'
android: I/flutter : Receiver: Type: class 'CustomPaint'
android: I/flutter : Tried calling: CustomPaint(onPaint: Closure: (PaintingCanvas, Size) => void from Function 'paintCallback':., token: Instance of '_TextureButtonToken')
android: I/flutter : Found: CustomPaint({key: Key, painter: dynamic, child: Widget})
android: I/flutter : Stack trace:
android: I/flutter : #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:188)
android: I/flutter : #1      TextureButtonState.build (/usr/local/google/home/brettmorgan/github/game/lib/main.dart:187)
android: I/flutter : #2      ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1070)
android: I/flutter : #3      BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1011)
android: I/flutter : #4      StatefulComponentElement.update (packages/flutter/src/widgets/framework.dart:1169)
android: I/flutter : #5      Element.updateChild (packages/flutter/src/widgets/framework.dart:642)
android: I/flutter : #6      RenderObjectElement.updateChildren (packages/flutter/src/widgets/framework.dart:1468)
android: I/flutter : #7      MultiChildRenderObjectElement.update (packages/flutter/src/widgets/framework.dart:1662)
android: I/flutter : #8      Element.updateChild (packages/flutter/src/widgets/framework.dart:642)
android: I/flutter : #9      RenderObjectElement.updateChildren (packages/flutter/src/widgets/framework.dart:1468)
android: I/flutter : #10     MultiChildRenderObjectElement.update (packages/flutter/src/widgets/framework.dart:1662)
android: I/flutter : #11     Element.updateChild (packages/flutter/src/widgets/framework.dart:642)
android: I/flutter : #12     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1082)
android: I/flutter : #13     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1011)
android: I/flutter : #14     ProxyElement.update (packages/flutter/src/widgets/framework.dart:1206)
android: I/flutter : #15     Element.updateChild (packages/flutter/src/widgets/framework.dart:642)
android: I/flutter : #16     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1082)
android: I/flutter : #17     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1011)
android: I/flutter : #18     StatelessComponentElement.update (packages/flutter/src/widgets/framework.dart:1115)
android: I/flutter : #19     Element.updateChild (packages/flutter/src/widgets/framework.dart:642)
android: I/flutter : #20     OneChildRenderObjectElement.update (packages/flutter/src/widgets/framework.dart:1578)
android: I/flutter : #21     Element.updateChild (packages/flutter/src/widgets/framework.dart:642)
android: I/flutter : #22     OneChildRenderObjectElement.update (packages/flutter/src/widgets/framework.dart:1578)
android: I/flutter : #23     Element.updateChild (packages/flutter/src/widgets/framework.dart:642)
android: I/flutter : #24     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1082)
android: I/flutter : #25     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1011)
android: I/flutter : #26     StatefulComponentElement.update (packages/flutter/src/widgets/framework.dart:1169)
android: I/flutter : #27     Element.updateChild (packages/flutter/src/widgets/framework.dart:642)
android: I/flutter : #28     OneChildRenderObjectElement.update (packages/flutter/src/widgets/framework.dart:1578)
android: I/flutter : #29     Element.updateChild (packages/flutter/src/widgets/framework.dart:642)
android: I/flutter : #30     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1082)
android: I/flutter : #31     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1011)
android: I/flutter : #32     ProxyElement.update (packages/flutter/src/widgets/framework.dart:1206)
android: I/flutter : #33     Element.updateChild (packages/flutter/src/widgets/framework.dart:642)
android: I/flutter : #34     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1082)
android: I/flutter : #35     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1011)
android: I/flutter : #36     StatefulComponentElement.update (packages/flutter/src/widgets/framework.dart:1169)
android: I/flutter : #37     Element.updateChild (packages/flutter/src/widgets/framework.dart:642)
android: I/flutter : #38     OneChildRenderObjectElement.update (packages/flutter/src/widgets/framework.dart:1578)
android: I/flutter : #39     Element.updateChild (packages/flutter/src/widgets/framework.dart:642)
android: I/flutter : #40     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1082)
android: I/flutter : #41     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1011)
android: I/flutter : #42     StatefulComponentElement.update (packages/flutter/src/widgets/framework.dart:1169)
android: I/flutter : #43     Element.updateChild (packages/flutter/src/widgets/framework.dart:642)
android: I/flutter : #44     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1082)
android: I/flutter : #45     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1011)
android: I/flutter : #46     StatelessComponentElement.update (packages/flutter/src/widgets/framework.dart:1115)
android: I/flutter : #47     Element.updateChild (packages/flutter/src/widgets/framework.dart:642)
android: I/flutter : #48     RenderObjectElement.updateChildren (packages/flutter/src/widgets/framework.dart:1468)
android: I/flutter : #49     MultiChildRenderObjectElement.update (packages/flutter/src/widgets/framework.dart:1662)
android: I/flutter : #50     Element.updateChild (packages/flutter/src/widgets/framework.dart:642)
android: I/flutter : #51     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1082)
android: I/flutter : #52     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1011)
android: I/flutter : #53     WidgetFlutterBinding.buildDirtyElements.<anonymous closure> (packages/flutter/src/widgets/binding.dart:58)
android: I/flutter : #54     BuildableElement.lockState (packages/flutter/src/widgets/framework.dart:944)
android: I/flutter : #55     WidgetFlutterBinding.buildDirtyElements (packages/flutter/src/widgets/binding.dart:53)
android: I/flutter : #56     WidgetFlutterBinding.beginFrame (packages/flutter/src/widgets/binding.dart:28)
android: I/flutter : #57     FlutterBinding._handlePersistentFrameCallback (packages/flutter/src/rendering/binding.dart:186)
android: I/flutter : #58     Scheduler.invokeCallback (packages/flutter/src/animation/scheduler.dart:90)
android: I/flutter : #59     Scheduler.beginFrame (packages/flutter/src/animation/scheduler.dart:75)
android: I/flutter : #60     _beginFrame (file:///src/flutter/engine/src/out/android_Release/gen/sky/bindings/Customhooks.dart:45)
```

**Comment by eseidelGoogle** [comment]
I believe this was a mismatch between the version of flutter the game was using and the latest flutter.  I believe @vlidholt is in the process of updating the game now.

**Comment by vlidholt** [comment]
This should be fixed
